apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistentvolumeclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
