apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-persistentvolume
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/redis"